### ISSUE TITLE
Python code problem with 'copy'

### ISSUE THREAD

**Issue by byzantic** [byzantic/piecewiseconstants#1]
First attempt to run demo.py resulted in this error:

Traceback (most recent call last):
  File "demo.py", line 56, in <module>
    x[:,7] = pwc_jumppenalty(y);
  File "/home/rob/work/maths/toolkits/pwctools/pwc_jumppenalty.py", line 84, in pwc_jumppenalty
    r1 = r.copy()
AttributeError: 'list' object has no attribute 'copy'

**Comment by byzantic** [comment]
Fixed by changing line 84 to:
            r1 = list(r)
